/**
 * @type {char offset}
 * **[Attack type](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x0)**
 * - 0 ⟶ None
 * - 1 ⟶ **[Melee](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x0_1)**
 * - 2 ⟶ **[Ranged](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x0_2)**
 * - 3 ⟶ **[Magical](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x0_3)**
 * - 4 ⟶ **[Launcher](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x0_4)**
 * For [`Item`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x2_3) abilities:
 * - Do NOT use `0|None`, will crash the game.
 * - Only [`Magical`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x0_3) abilities can be drained (along with [opcode #243](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op243)'s other restrictions).
 * - Type [`4`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x0_4) cannot be used except from scripts (icon won't show up in actionbar).
 * For [`Weapon`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x2_1) abilities:
 * - Do NOT use `0|None`, will crash the game.
 * - [`Melee`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x0_1): Ignores the [`projectile`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x2A) field (always uses `#1|None`). Valid for [Weapon Styles](https://gibberlings3.github.io/iesdp/files/2da/2da_bgee/stylbonu.htm).
 * - [`Ranged`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x0_2):
 *   - Utilizes [`projectile`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x2A) field.
 *   - Item cannot be equipped in [`off-hand`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#9), unless its [`itemtype`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#Header_ItemType) can only be equipped in the [`off-hand`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#9) slot, from [`ITEMTYPE.2DA`](https://gibberlings3.github.io/iesdp/files/2da/2da_bgee/itemtype.htm).
 *   - If equipped in [`off-hand`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#9), it will attack as normal (at least for the offhand).
 *   - [`Off-hand`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#9) weapon will be suppressed while this item ability is selected in [`mainhand`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#35) (EE only).
 * - [`Magical`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x0_3): Identical to [`Melee`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x0_1), except that it can be [drained](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op243).
 * - [`Launcher`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x0_4):
 *   - In the [`mainhand`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#35) slots:
 *     - Ability cannot actually be selected, nor is the item considered "equipped" by script triggers or [opcode #183](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op183).
 *     - Equipped effects, stats and on-hit effects are added to the currently selected weapon ability IF that ability requires a [`launcher`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x10) of this type.
 *   - In the [`off-hand`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#9) slot:
 *     - Item cannot be equipped in [`off-hand`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#9), unless its [`itemtype`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#Header_ItemType) can only be equipped in the [`off-hand`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#9) slot, from [`ITEMTYPE.2DA`](https://gibberlings3.github.io/iesdp/files/2da/2da_bgee/itemtype.htm).
 *     - Attack cycle will stop when this weapon would have attacked (must be re-initiated manually or by script).
 *       - The creature will stop attacking when the off-hand attack would have occurred. Similar to pressing the group "Stop" button (F3).
 */
OUTER_SET ITM_HEAD_attack_type = 0x0

/**
 * @type {char offset}
 * ID Req.
 * - bit 0 ⟶ ID Required
 * - bit 1 ⟶ Non-ID Required
 */
OUTER_SET ITM_HEAD_id_required = 0x1

/**
 * @type {char offset}
 * **[Location](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x2)**
 * - 0 ⟶ None
 *   - Ability will not be selectable through the UI (but still available to scripts and spell-casting opcodes).
 * - 1 ⟶ **[Weapon](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x2_1)**
 *   - Ability can be used/selected in Quick-weapon slots (when equipped in one of the [`mainhand`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#35)/[`ammo`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#11)/[`fist`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#10)/[`magical weapon`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#34) slots).
 * - 2 ⟶ Spell
 *   - [`SPL`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0x2_2) only.
 * - 3 ⟶ **[Equipment / Item](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x2_3)**
 *   - Ability can be selected from Quick-item slots, when equipped in one of those slots, or from the "Use Item (F8)" button if equipped elsewhere (except the [`Magical Weapon Slot`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#34)).
 * - 4 ⟶ Innate
 *   - [`SPL`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0x2_4) only.
 * - 5+ ⟶ As `0`.
 * The first ability header of an item equipped in a [`weapon`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#35)/[`off-hand`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#9) slot will always be treated as a [`weapon`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x2_1) abillty, even if it lacks the correct [`location`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x2) to be selected as such, unless that item is a [`shield`](https://gibberlings3.github.io/iesdp/files/ids/bgee/itemcat.htm#12) in the [`off-hand`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#9).
 */
OUTER_SET ITM_HEAD_location = 0x2

/**
 * @type {char offset}
 * Alternative dice sides
 */
OUTER_SET ITM_HEAD_alt_dice_sides = 0x3

/**
 * @type {resref offset}
 * Use icon
 */
OUTER_SET ITM_HEAD_use_icon = 0x4

/**
 * @type {char offset}
 * **[Target type](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0xC)**
 * - 0 ⟶ Invalid (cannot be selected)
 * - 1 ⟶ **[Living actor](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0xC_1)**
 *   - Targets Portrait, [Creature/Actor](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v1.htm#formAREAV1_0_Actor), [Container](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v1.htm#formAREAV1_0_Container), or [Door](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v1.htm#formAREAV1_0_Door). Checks [`Range`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0xE).
 * - 2 ⟶ **[Inventory](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0xC_2)**
 *   - Can't be activated manually.
 * - 3 ⟶ **[Dead actor](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0xC_3)**
 *   - As [`Living Actor`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0xC_1). It really just ignores any [`Range`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0xE) requirement, including being in the same area.
 * - 4 ⟶ **[Any point within range](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0xC_4)**
 *   - Targets location. Checks [`Range`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0xE).
 * - 5 ⟶ **[Caster](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0xC_5)**
 *   - Targets Self.
 * - 6 ⟶ Crash
 *   - Can't be activated manually.
 * - 7 ⟶ **[Caster](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0xC_7)** (EE only)
 *   - Targets Self. In particular:
 *     - Used instantly (even while the game is paused).
 *     - Ignores one item per round rule.
 *     - Ignores [`projectile`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x2A) (uses `#1|None`).
 * - This field doesn't matter when the ability is activated/cast by script, when cast by another opcode, or for weapon attacks.
 * - [`Weapon`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x2_1) attacks always use a more restricted form of [`Living actor`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0xC_1), as they cannot target [containers](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v1.htm#formAREAV1_0_Container) or [doors](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v1.htm#formAREAV1_0_Door) unless they are locked.
 */
OUTER_SET ITM_HEAD_target = 0xc

/**
 * @type {char offset}
 * **[Target count](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0xD)**
 * - Only usable by [`Item`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x2_3) abilities, and only with Ability Targets [`1`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0xC_1), [`3`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0xC_3), or [`4`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0xC_4).
 * - Targeting reticle will display amount remaining while selecting targets.
 * - Double-clicking a target/location will target it for the remaining amount.
 * - Regardless of the number of targets, only a single "Charge" will be expended.
 * - This feature cannot be utilized by scripts.
 *   - Scripts will treat this field as if it's always `1`.
 */
OUTER_SET ITM_HEAD_target_count = 0xd

/**
 * @type {word offset}
 * **[Range](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0xE)**
 */
OUTER_SET ITM_HEAD_range = 0xe

/**
 * @type {byte offset}
 * **[Launcher required](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x10)**
 * - 0 ⟶ None
 * - 1 ⟶ **[Bow](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x10_1)**
 *   - Any [`Ranged`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x0_2) ability with this field set to this value will require a weapon with the corresponding [`ITEMCAT.IDS`](https://gibberlings3.github.io/iesdp/files/ids/bgee/itemcat.htm#15) (Item category) in one of the [`mainhand`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#35) weapon slots (not [`off-hand`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#9), [`fist`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#10), or [`magical weapon`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#34) slot).
 * - 2 ⟶ **[Crossbow](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x10_2)**
 *   - Any [`Ranged`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x0_2) ability with this field set to this value will require a weapon with the corresponding [`ITEMCAT.IDS`](https://gibberlings3.github.io/iesdp/files/ids/bgee/itemcat.htm#27) (Item category) in one of the [`mainhand`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#35) weapon slots (not [`off-hand`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#9), [`fist`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#10), or [`magical weapon`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#34) slot).
 * - 3 ⟶ **[Sling](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x10_3)**
 *   - Any [`Ranged`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x0_2) ability with this field set to this value will require a weapon with the corresponding [`ITEMCAT.IDS`](https://gibberlings3.github.io/iesdp/files/ids/bgee/itemcat.htm#18) (Item category) in one of the [`mainhand`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#35) weapon slots (not [`off-hand`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#9), [`fist`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#10), or [`magical weapon`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#34) slot).
 * - 40 ⟶ Spear
 * - 100 ⟶ Throwing Axe
 * In particular:
 * - It ONLY checks items for [`BOW`](https://gibberlings3.github.io/iesdp/files/ids/bgee/itemcat.htm#15) / [`XBOW`](https://gibberlings3.github.io/iesdp/files/ids/bgee/itemcat.htm#27) / [`SLING`](https://gibberlings3.github.io/iesdp/files/ids/bgee/itemcat.htm#18) and will always use that item's first ability header – it doesn't matter what that ability's [`Type`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x0) is ([`Melee`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x0_1)/[`Ranged`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x0_2)/[`Magical`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x0_3)/[`Launcher`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x0_4)).
 *   - This also means that you can't make an Arrow that requires being shot out of a Sword.
 * - [`ITEMCAT`](https://gibberlings3.github.io/iesdp/files/ids/bgee/itemcat.htm) is offset [`0x1C`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#Header_ItemType) of the ITM file (which is also linked to [`ITEMTYPE.2DA`](https://gibberlings3.github.io/iesdp/files/2da/2da_bgee/itemtype.htm)).
 * - Only the [`Mainhand`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#35), [`Ammo`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#11), and [`Magical Weapon`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#34) slots can utilize launchers. The [`off-hand`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#9) ignores this field, while the [`fist`](https://gibberlings3.github.io/iesdp/files/ids/bgee/slots.htm#10) slot uses it (only to crash).
 * - Weapons of any [`ITEMCAT`](https://gibberlings3.github.io/iesdp/files/ids/bgee/itemcat.htm) can use this field, as long as it is equipped in one of the proper slots.
 *   - This also means that you can make a Sword that requires being shot out of a Bow.
 * - Bows, Crossbows, and Slings with multiple abilities can even use themselves as their required launcher.
 */
OUTER_SET ITM_HEAD_projectile_type = 0x10

/**
 * @type {byte offset}
 * Alternative dice thrown
 */
OUTER_SET ITM_HEAD_alt_dice_thrown = 0x11

/**
 * @type {byte offset}
 * **[Speed Factor](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_SpeedFactor)**
 * - See [opcode #190](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op190).
 */
OUTER_SET ITM_HEAD_speed = 0x12

/**
 * @type {byte offset}
 * Alternative damage bonus
 */
OUTER_SET ITM_HEAD_alt_damage_bonus = 0x13

/**
 * @type {word offset}
 * THAC0 bonus
 * A successful hit will always occur if any of the conditions below is true
 * - This field is set to `32767`.
 * - The target creature(s) is `STATE_HELPLESS`.
 * - The target is affected by [Time Stop](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op231).
 */
OUTER_SET ITM_HEAD_thac0_bonus = 0x14

/**
 * @type {byte offset}
 * **[Dice sides](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x16)**
 */
OUTER_SET ITM_HEAD_dice_sides = 0x16

/**
 * @type {byte offset}
 * **[Primary Type (School)](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x17)**
 * - See [`MSCHOOL.2DA`](https://gibberlings3.github.io/iesdp/files/2da/2da_bgee/mschool.htm).
 */
OUTER_SET ITM_HEAD_primary_type = 0x17

/**
 * @type {byte offset}
 * **[Dice thrown](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x18)**
 */
OUTER_SET ITM_HEAD_dice_thrown = 0x18

/**
 * @type {byte offset}
 * **[Secondary Type](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x19)**
 * - See [`MSECTYPE.2DA`](https://gibberlings3.github.io/iesdp/files/2da/2da_bgee/msectype.htm).
 */
OUTER_SET ITM_HEAD_secondary_type = 0x19

/**
 * @type {word offset}
 * **[Damage bonus](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x1A)**
 */
OUTER_SET ITM_HEAD_damage_bonus = 0x1a

/**
 * @type {word offset}
 * **[Damage type](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x1C)**
 * - 0 ⟶ **[None](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x1C_0)**
 *   - Deals Crushing damage, uses base AC (ignores all 4 specific AC).
 *     - If [`#dice`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x18): Deals damage as normal, just no dice amount.
 *     - If [`#dice`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x18): Sets target's HP to `Damage Dealt`, ignores crushing resistance.
 * - 1 ⟶ **[Piercing](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x1C_1)**
 * - 2 ⟶ **[Crushing](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x1C_2)**
 * - 3 ⟶ **[Slashing](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x1C_3)**
 * - 4 ⟶ **[Missile](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x1C_4)**
 * - 5 ⟶ **[Fist](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x1C_5)**
 *   - Deals non-lethal damage, but uses Crushing AC.
 * - 6 ⟶ **[Piercing/Crushing](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x1C_6)** (Better)
 *   - Uses whichever damage type and AC the creature has the worst damage resistance against (regardless if its AC is better or worse). Uses `Piercing` if equal resistance.
 * - 7 ⟶ **[Piercing/Slashing](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x1C_7)** (Better)
 *   - Uses whichever damage type and AC the creature has the worst damage resistance against (regardless if its AC is better or worse). Uses `Piercing` if equal resistance.
 * - 8 ⟶ **[Crushing/Slashing](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x1C_8)** (Worse)
 *   - Uses whichever damage type and AC the creature has the better damage resistance against (regardless if its AC is better or worse). Uses `Slashing` if equal resistance.
 * - 9 ⟶ **[Blunt Missile](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x1C_9)**
 *   - Same as [`None`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x1C_0)
 *     - Either it's bugged or [`Blunt Missile`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x1C_9) has always been an IWD2-only feature.
 *     - It's probably meant to deal crushing damage while using Missile AC.
 * - 10+ ⟶ Same as [`None`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x1C_0)
 * - ALL values:
 *   - If [`Dice thrown`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x18), [`Dice size`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x16), and [`Damage bonus`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x1A) are all `0`: Always deals zero damage (ignores all modifiers, like Weapon Proficiency).
 *     - If you want zero base damage + modifiers, you can use `1d1 - 1`.
 *   - Some edge cases:
 *     - [`Dice thrown`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x18): Deals `X` damage, regardless of other modifiers.
 *     - [`Dice thrown`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x18): Deals `X + modifiers` damage.
 *     - [`Dice thrown`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x18): Also deals `0` damage.
 * - Values `1–4` don't have any other quirks ([`Piercing`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x1C_1), [`Crushing`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x1C_2), [`Slashing`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x1C_3), [`Missile`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x1C_4)), just each a different damage type.
 */
OUTER_SET ITM_HEAD_damage_type = 0x1c

/**
 * @type {word offset}
 * Count of feature blocks
 */
OUTER_SET ITM_HEAD_feature_block_count = 0x1e

/**
 * @type {word offset}
 * Index into feature blocks
 */
OUTER_SET ITM_HEAD_feature_block_index = 0x20

/**
 * @type {word offset}
 * **[Max Charges](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x22)**
 */
OUTER_SET ITM_HEAD_max_charges = 0x22

/**
 * @type {word offset}
 * **[Charge depletion behaviour](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x24)**
 * - 0 ⟶ **[Item remains](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x24_0)**
 *   - Item becomes unusable (except as a weapon) when [`Max Charges`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x22) reaches zero. Can be recharged by selling or by resting if it has the [`Recharge after resting`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#ExtHeader_Flags_BIT11) flag.
 * - 1 ⟶ **[Item vanishes](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x24_1)**
 *   - Item disappears when [`Max Charges`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x22) reaches zero. Can be recharged prior to reaching zero (through either method).
 * - 2 ⟶ **[Replace with used up](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x24_2)**
 *   - When [`Max Charges`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x22) reaches zero, item is replaced with the item specified at offset [`0x10`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Header_0x10). Can be recharged prior to reaching zero (through either method).
 * - 3 ⟶ **[Item recharges](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x24_3)**
 *   - This is very likely no different from [`Item remains`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x24_0) or `4+`, i.e. defaults to [`0`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x24_0).
 * - This field is irrelevant when the [`Max Charges`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x22) field is zero. Item can be used infinitely.
 * - If the item has a [`Max Stack Size`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Header_0x38), this behavior will instead occur when the stack is depleted, not the charges (but still requires a non-zero [`Max Charges`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x22)).
 */
OUTER_SET ITM_HEAD_depletion = 0x24

/**
 * @type {dword offset}
 * [Flags](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#ExtHeader_Flags)
 */
OUTER_SET ITM_HEAD_flags = 0x26

/**
 * @type {word offset}
 * **[Projectile Animation](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x2A)** (projectl.ids/missile.ids)
 */
OUTER_SET ITM_HEAD_projectile_animation = 0x2a

/**
 * @type {word offset}
 * **[Melee animation](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#ExtendedHeader_MeleeAnimation)**
 * - It should total 100, but not mandatory on EE games.
 * - Not needed if [`Arrow`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x32)/[`Bolt`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x34)/[`Bullet`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x36) is used.
 * - It should work as such:
 *   Engine rolls `0 – 99`.
 *   - `overhand range = 0 to (overhand - 1)`
 *   - `backhand range = overhand to (overhand + backhand - 1)`
 *   - `thrust range = (overhand + backhand) to (overhand + backhand + thrust - 1)`
 *   A couple of examples:
 *   - With values `34`, `33`, and `33`:
 *     - `0 – 33`: Overhand
 *     - `34 – 66`: Backhand
 *     - `67 – 99`: Thrust
 *   - With values `100`, `100`, `100`:
 *     - `0 – 99`: Overhand
 *     - `100 – 199`: Backhand (never used)
 *     - `200 – 299`: Thrust (never used)
 * - Along with [`Is arrow?`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x32)/[`Is bolt?`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x34)/[`Is bullet?`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x36), it is only used for attack animations. If all are zero, no animation will be used for attacking. Activated [`Item`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x2_3) abilities can leave them all `0`, as they are not used.
 */
OUTER_SET ITM_HEAD_melee_animation = 0x2c

/**
 * @type {word offset}
 * **[Arrow qualifier / Is arrow?](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x32)**
 * - 0 ⟶ No
 * - 1 ⟶ Yes
 * It controls which firing animation the ability will use.
 * It needs to be set on any launcher and/or ammo, but the launcher will override the ammo.
 */
OUTER_SET ITM_HEAD_is_arrow = 0x32

/**
 * @type {word offset}
 * **[Bolt qualifier / Is bolt?](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x34)**
 * - 0 ⟶ No
 * - 1 ⟶ Yes
 * It controls which firing animation the ability will use.
 * It needs to be set on any launcher and/or ammo, but the launcher will override the ammo.
 */
OUTER_SET ITM_HEAD_is_bolt = 0x34

/**
 * @type {word offset}
 * **[Bullet qualifier / Is bullet?](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x36)**
 * - 0 ⟶ No
 * - 1 ⟶ Yes
 * It controls which firing animation the ability will use.
 * It needs to be set on any launcher and/or ammo, but the launcher will override the ammo.
 */
OUTER_SET ITM_HEAD_is_bullet = 0x36

/**
 * @type {char array offset}
 * Signature ('ITM ')
 */
OUTER_SET ITM_signature = 0x0

/**
 * @type {char array offset}
 * Version ('V1  ')
 */
OUTER_SET ITM_version = 0x4

/**
 * @type {strref offset}
 * Unidentified Name (strref)
 */
OUTER_SET ITM_unidentified_name = 0x8

/**
 * @type {strref offset}
 * Identified Name (strref)
 */
OUTER_SET ITM_identified_name = 0xc

/**
 * @type {resref offset}
 * BG1, BG2, BGEE:
 * **[Replacement item](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Header_0x10)** (ITM)
 * PSTEE:
 * Drop sound - played when the item is dropped in the inventory (WAV)
 */
OUTER_SET ITM_replacement = 0x10

/**
 * @type {dword offset}
 * [Flags](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#Header_Flags)
 */
OUTER_SET ITM_flags = 0x18

/**
 * @type {word offset}
 * [Item type](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#Header_ItemType)
 */
OUTER_SET ITM_type = 0x1c

/**
 * @type {byte offset}
 * [Usability bitmask](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#Header_Usability)
 */
OUTER_SET ITM_usability_flags = 0x1e

/**
 * @type {char array offset}
 * [Item animation](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#Header_Animation)
 */
OUTER_SET ITM_animation = 0x22

/**
 * @type {word offset}
 * **[Min Level](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Header_0x24)**
 * - Treated as average of all active class levels, rounded up.
 * - This field is basically the ITM counterpart of [`Level Required`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0x10).
 * - The only difference is that ITM [abilities](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header) cannot have separate level requirements.
 */
OUTER_SET ITM_min_level = 0x24

/**
 * @type {word offset}
 * Min Strength (unused in BG1)
 */
OUTER_SET ITM_min_strength = 0x26

/**
 * @type {byte offset}
 * Min Strength Bonus (unused in BG1)
 * Note: A strength of 19 or above is considered to have a Strength Bonus of 0, and would therefore not be able to equip any weapon with a Strength Bonus restriction.
 */
OUTER_SET ITM_min_strength_bonus = 0x28

/**
 * @type {byte offset}
 * [Kit Usability 1](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#Header_KitUsability)
 */
OUTER_SET ITM_kit_usability1 = 0x29

/**
 * @type {byte offset}
 * Min Intelligence (unused in BG1)
 */
OUTER_SET ITM_min_intelligence = 0x2a

/**
 * @type {byte offset}
 * [Kit Usability 2](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#Header_KitUsability)
 */
OUTER_SET ITM_kit_usability2 = 0x2b

/**
 * @type {byte offset}
 * Min Dexterity (unused in BG1)
 */
OUTER_SET ITM_min_dexterity = 0x2c

/**
 * @type {byte offset}
 * [Kit Usability 3](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#Header_KitUsability)
 */
OUTER_SET ITM_kit_usability3 = 0x2d

/**
 * @type {byte offset}
 * Min Wisdom (unused in BG1)
 */
OUTER_SET ITM_min_wisdom = 0x2e

/**
 * @type {byte offset}
 * [Kit Usability 4](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#Header_KitUsability)
 */
OUTER_SET ITM_kit_usability4 = 0x2f

/**
 * @type {byte offset}
 * Min Constitution (unused in BG1)
 */
OUTER_SET ITM_min_constitution = 0x30

/**
 * @type {byte offset}
 * [Weapon Proficiency](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#Header_Proficiency)
 */
OUTER_SET ITM_weapon_proficiency = 0x31

/**
 * @type {word offset}
 * Min Charisma
 */
OUTER_SET ITM_min_charisma = 0x32

/**
 * @type {dword offset}
 * Price
 */
OUTER_SET ITM_price = 0x34

/**
 * @type {word offset}
 * **[Stack amount](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Header_0x38)**
 */
OUTER_SET ITM_stack_amount = 0x38

/**
 * @type {resref offset}
 * Inventory icon (BAM)
 */
OUTER_SET ITM_inventory_icon = 0x3a

/**
 * @type {word offset}
 * Lore to ID
 */
OUTER_SET ITM_lore_to_id = 0x42

/**
 * @type {resref offset}
 * **[Ground icon](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Header_0x44)** (BAM)
 */
OUTER_SET ITM_ground_icon = 0x44

/**
 * @type {dword offset}
 * Weight
 */
OUTER_SET ITM_weight = 0x4c

/**
 * @type {strref offset}
 * Unidentified Description (strref)
 */
OUTER_SET ITM_unidentified_desc = 0x50

/**
 * @type {strref offset}
 * Identified Description (strref)
 */
OUTER_SET ITM_identified_desc = 0x54

/**
 * @type {resref offset}
 * Description icon (BAM)
 */
OUTER_SET ITM_description_icon = 0x58

/**
 * @type {dword offset}
 * **[Enchantment](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Header_0x60)**
 */
OUTER_SET ITM_enchantment = 0x60

/**
 * @type {dword offset}
 * Offset to extended headers
 */
OUTER_SET ITM_extended_headers_offset = 0x64

/**
 * @type {word offset}
 * Count of extended headers
 */
OUTER_SET ITM_extended_headers_count = 0x68

/**
 * @type {dword offset}
 * Offset to feature blocks
 */
OUTER_SET ITM_feature_blocks_offset = 0x6a

/**
 * @type {word offset}
 * Index into equipping feature blocks
 */
OUTER_SET ITM_feature_blocks_index = 0x6e

/**
 * @type {word offset}
 * Count of equipping feature blocks
 */
OUTER_SET ITM_feature_blocks_count = 0x70
