/**
 * @type {word offset}
 * Opcode Number
 */
OUTER_SET FX_opcode = 0x0

/**
 * @type {char offset}
 * **[Target type](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x2)**
 * - 0 ⟶ None
 * - 1 ⟶ **[Self](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x2_1)**
 * - 2 ⟶ **[Projectile target](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x2_2)**
 * - 3 ⟶ **[Party](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x2_3)**
 * - 4 ⟶ **[Everyone](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x2_4)**
 * - 5 ⟶ **[Everyone except party](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x2_5)**
 * - 6 ⟶ **[Caster group](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x2_6)**
 * - 7 ⟶ **[Target group](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x2_7)**
 * - 8 ⟶ **[Everyone except self](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x2_8)**
 * - 9 ⟶ **[Original caster](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x2_9)**
 * See [here](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2) for further details.
 */
OUTER_SET FX_target = 0x2

/**
 * @type {char offset}
 * Power
 */
OUTER_SET FX_power = 0x3

/**
 * @type {dword offset}
 * Parameter 1
 */
OUTER_SET FX_parameter1 = 0x4

/**
 * @type {dword offset}
 * Parameter 2
 */
OUTER_SET FX_parameter2 = 0x8

/**
 * @type {char offset}
 * **[Timing mode](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0xC)**
 * - 0 ⟶ **[Instant/Limited](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0xC_0)**
 * - 1 ⟶ **[Instant/Permanent](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0xC_1)**
 * - 2 ⟶ **[Instant/While equipped](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0xC_2)**
 * - 3 ⟶ **[Delay/Limited](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0xC_3)**
 * - 4 ⟶ **[Delay/Permanent](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0xC_4)**
 * - 5 ⟶ **[Delay/While equipped](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0xC_5)**
 * - 6 ⟶ **[Limited after duration](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0xC_6)**
 * - 7 ⟶ **[Permanent after duration](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0xC_7)**
 * - 8 ⟶ **[Equipped after duration](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0xC_8)**
 * - 9 ⟶ **[Instant/Permanent](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0xC_9)** (after Death)
 * - 10 ⟶ **[Instant/Limited](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0xC_10)**
 * - 4096 ⟶ **[Absolute duration](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0xC_4096)**
 * See [here](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC) for further details.
 */
OUTER_SET FX_timing = 0xc

/**
 * @type {char offset}
 * **[Dispel / Resistance](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0xD)**
 * The default behaviour is that effects cannot be dispelled and ignore magic resistance.
 * - bit 0 ⟶ Can be dispelled, affected by magic resistance
 * - bit 1 ⟶ Ignores magic resistance (when used in combination with bit 0)
 * This can also be presented in the more traditional way:
 * - 0 ⟶ Natural/Nonmagical
 * - 1 ⟶ Can be dispelled/Affected by resistance
 * - 2 ⟶ Cannot be dispelled/Ignores resistance
 * - 3 ⟶ Can be dispelled/Ignores resistance
 * The only difference between `0` and `2` is that `0` will automatically convert to `2` when targeting yourself.
 */
OUTER_SET FX_resistance = 0xd

/**
 * @type {dword offset}
 * **[Duration](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0xE)**
 */
OUTER_SET FX_duration = 0xe

/**
 * @type {char offset}
 * **[Probability 1](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x12)**
 */
OUTER_SET FX_probability1 = 0x12

/**
 * @type {char offset}
 * **[Probability 2](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x13)**
 * See [here](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x13) for further details.
 */
OUTER_SET FX_probability2 = 0x13

/**
 * @type {resref offset}
 * Resource
 */
OUTER_SET FX_resource = 0x14

/**
 * @type {dword offset}
 * **[Dice Thrown / Maximum Level](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x1C)**
 * See [here](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x1C) for further details.
 */
OUTER_SET FX_max_level = 0x1c

/**
 * @type {dword offset}
 * **[Dice Sides / Minimum Level](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x20)**
 * See [here](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x20) for further details.
 */
OUTER_SET FX_min_level = 0x20

/**
 * @type {dword offset}
 * **[Saving throw type](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x24)**
 * - bit 0 ⟶ **[Spells](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x24_BIT0)**
 * - bit 1 ⟶ **[Breath](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x24_BIT1)**
 * - bit 2 ⟶ **[Paralyze / Poison / Death](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x24_BIT2)**
 * - bit 3 ⟶ **[Wands](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x24_BIT3)**
 * - bit 4 ⟶ **[Petrify / Polymorph](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x24_BIT4)**
 * - bit 10 ⟶ **[Ignore primary target](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x24_BIT10)** (EE only)
 * - bit 11 ⟶ **[Ignore secondary target](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x24_BIT11)** (EE only)
 * - bit 24 ⟶ **[Bypass mirror image](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x24_BIT24)** (EE/TobEx only)
 * - bit 25 ⟶
 *   - **[Ignore difficulty](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x24_BIT25_EE)** (EE only)
 *   - **[Limit effect stacking](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#V1_Feature_Block_0x24_BIT25_ToBEx)** (ToBEx only)
 * - bit 26 ⟶ TobEx internal (don't use)
 * See [here](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x24) for further details.
 */
OUTER_SET FX_save_type = 0x24

/**
 * @type {dword offset}
 * Saving Throw Bonus
 */
OUTER_SET FX_save_bonus = 0x28

/**
 * @type {dword offset}
 * TobEx: Stacking ID. Checked when bit 25 of the Saving Throw Type is set.
 * If two effects of the same opcode are applied, both have Limit Effect Stacking bit set, and both have the same stacking ID, then the latter applied effect is suspended in application until the former effect expires. Regardless of whether it is applied, the latter effect will expire at the same time that it would expire if it was applied. In other words, the total duration of some non-stacking effect opcode is not extended because more than one copy of the effect was applied.
 * Stacking IDs are unique to the opcode being applied. To maintain uniqueness of stacking IDs between different mods, one recommendation is to use the higher word of Special as the modder's Infinity Engine Community Prefix, then use the lower word as an identifying ID. For example, 0x41360001 ('A6' 0x0001).
 */
OUTER_SET FX_stacking_id_Ex = 0x2c
