/**
 * @type {word offset}
 * Effect type
 */
OUTER_SET EFF_effect_type = 0x0

/**
 * @type {byte offset}
 * **[Target type](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2)**
 * - 0 ⟶ None
 * - 1 ⟶ **[Self](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_1)**
 * - 2 ⟶ **[Projectile target](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_2)**
 *   - Affects each target of the specified projectile, as it impacts them.
 * - 3 ⟶ **[Party](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_3)**
 * - 4 ⟶ **[Everyone](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_4)**
 * - 5 ⟶ **[Everyone except party](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_5)**
 * - 6 ⟶ **[Caster group](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_6)**
 *   - Everyone matching [`specific`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/cre_v1.htm#CREV1_0_Header_0x274) value of caster.
 *   - If cast by a party member, then it functions as [`Party`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_3).
 *   - Ability target ([`ITM`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0xC)) doesn't matter.
 * - 7 ⟶ **[Target group](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_7)**
 *   - Everyone matching [`specific`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/cre_v1.htm#CREV1_0_Header_0x274) value of target.
 *   - Ability ([`ITM`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0xC)) must target a [creature](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v1.htm#formAREAV1_0_Actor), not a location, [container](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v1.htm#formAREAV1_0_Container), [door](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v1.htm#formAREAV1_0_Door), etc...
 * - 8 ⟶ **[Everyone except self](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_8)**
 * - 9 ⟶ **[Original caster](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_9)**
 *   - Affects Caster, as the specified projectile impacts its target(s), once or for each target depending on the projectile's flags (see [here](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/pro_v1.htm#ExtFlags_BIT31)). The specified projectile only determines when/if it's applied.
 * - `ITM` global (equipped) effects: Target is always the wearer, this field isn't relevant.
 * - `SPL` global (casting) effects: Will not work with [`Projectile Target`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_2).
 * - `Everyone` stands for "in current area".
 * - Excluding [`Target type`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2) [`2`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_2), all other [`Target type`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2)s apply the effect using projectile `#1|None`.
 * - [`Target type`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2)s [`2`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_2) and [`9`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_9) are applied in effect order, but always after the others, even when using projectile `#1|None`.
 *   - [`Target type`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2)s (`1`, `3–8`) are applied in effect order.
 *     - If a spell/item has effects listed in this order:
 *       - `op(1), target = 2`
 *       - `op(2), target = 3`
 *       - `op(3), target = 1`
 *       - `op(4), target = 9`
 *       - `op(5), target = 2`
 *       - `op(6), target = 6`
 *       They will be applied in this order:
 *       op(2), op(3), op(6), op(1), op(4), op(5).
 * - Similar to Melee Weapon Attacks, when [`Target type`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2)s other than [`1`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_1), [`2`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_2), [`9`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_9) apply the effect, they are subjected to [opcode #197](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op197) (`parameter2=0`) but not to [opcode #83](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op83). (Excluding when they're affecting the caster).
 * - Be aware that [opcode #146](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op146)`*p2=2`, [opcode #326](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op326), and [opcode #333](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op333) might behave differently when it comes to [`Self`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_1)/[`Projectile Target`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_2)/[`Original Caster`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_9).
 */
OUTER_SET EFF_target = 0x2

/**
 * @type {byte offset}
 * Power
 */
OUTER_SET EFF_power = 0x3

/**
 * @type {dword offset}
 * Parameter 1
 */
OUTER_SET EFF_parameter1 = 0x4

/**
 * @type {dword offset}
 * Parameter 2
 */
OUTER_SET EFF_parameter2 = 0x8

/**
 * @type {byte offset}
 * **[Timing mode](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC)**
 * - 0 ⟶ **[Instant/Limited](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_0)**
 *   - This timing mode measures [`Duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xE) in seconds.
 *   - Instantly converts to [`Absolute duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm#effv2_Body_0x24_4096), [`new duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm#effv2_Body_0x28).
 * - 1 ⟶ **[Instant/Permanent](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_1)**
 *   - If the opcode doesn't directly modify a [`STAT`](https://gibberlings3.github.io/iesdp/files/ids/bgee/stats.htm) in the target's [CRE](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/cre_v1.htm) file, then it will last until removed (or it self-terminates). [`New duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm#effv2_Body_0x28) (mostly unused).
 * - 2 ⟶ **[Instant/While equipped](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_2)**
 *   - As global `ITM` effect: Applied when item is equipped, lasts until item is unequipped (or [polymorph](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op135) bug).
 *     - "Equipping" also occurs when game loads, and for weapons whenever they are selected from quickbar (even if it's already the active weapon). Never expires, and not considered a "Limited" effect.
 *   - As `SPL` or header `ITM` effect: applies instantly, lasts until game is reloaded.
 *   - [`New duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm#effv2_Body_0x28) (mostly unused).
 * - 3 ⟶ **[Delay/Limited](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_3)**
 *   - This timing mode measures [`Duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xE) in seconds.
 *   - Instantly converts to [`Limited after duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_6), [`new duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm#effv2_Body_0x28).
 * - 4 ⟶ **[Delay/Permanent](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_4)**
 *   - This timing mode measures [`Duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xE) in seconds.
 *   - Instantly converts to [`Permanent after duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_7), [`new duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm#effv2_Body_0x28).
 * - 5 ⟶ **[Delay/While equipped](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_5)**
 *   - This timing mode measures [`Duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xE) in seconds.
 *   - Instantly converts to [`Equipped after duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_8), [`new duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm#effv2_Body_0x28).
 * - 6 ⟶ **[Limited after duration](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_6)**
 *   - This timing mode measures [`Duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xE) in ticks (1⁄15 second).
 *   - At [`Gametime`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/gam_v2.0.htm#GAMEV2_0_Header_GameTime) converts to [`Absolute duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm#effv2_Body_0x24_4096), [`new duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm#effv2_Body_0x28).
 *     - (If previously converted from [`Delay/Limited`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_3))
 *   - At [`Gametime`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/gam_v2.0.htm#GAMEV2_0_Header_GameTime) converts to [`Absolute duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm#effv2_Body_0x24_4096), [`new duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm#effv2_Body_0x28).
 *     - (If effect applied directly with [`Limited after duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_6))
 *     - `16 x Duration(ticks) = Duration(ticks) + 15 * Duration(seconds)` (Yes, it calculates a new duration using its current [`Duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xE) field as both ticks and seconds).
 *     - It will convert to [`Absolute duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm#effv2_Body_0x24_4096) at the same [`Gametime`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/gam_v2.0.htm#GAMEV2_0_Header_GameTime) (ticks) no matter when the effect was applied.
 *     - That [`Absolute duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm#effv2_Body_0x24_4096) will expire at the same [`Gametime`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/gam_v2.0.htm#GAMEV2_0_Header_GameTime) (ticks) no matter when the effect was applied.
 * - 7 ⟶ **[Permanent after duration](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_7)**
 *   - This timing mode measures [`Duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xE) in ticks (1⁄15 second).
 *   - At [`Gametime`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/gam_v2.0.htm#GAMEV2_0_Header_GameTime) converts to [`Instant/Permanent`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_1), [`new duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm#effv2_Body_0x28).
 *     - (If previously converted from [`Delay/Permanent`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_4))
 *   - At [`Gametime`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/gam_v2.0.htm#GAMEV2_0_Header_GameTime) converts to [`Instant/Permanent`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_1), [`new duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm#effv2_Body_0x28).
 *     - (If effect applied directly with [`Permanent after duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_7))
 *     - It will convert to [`Instant/Permanent`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_1) at the same [`Gametime`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/gam_v2.0.htm#GAMEV2_0_Header_GameTime) (ticks) no matter when the effect was applied.
 * - 8 ⟶ **[Equipped after duration](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_8)**
 *   - This timing mode measures [`Duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xE) in ticks (1⁄15 second).
 *   - At [`Gametime`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/gam_v2.0.htm#GAMEV2_0_Header_GameTime) converts to [`Instant/While equipped`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_2), [`new duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm#effv2_Body_0x28).
 * - 9 ⟶ **[Instant/Permanent](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_9)** (after Death)
 *   - Effect is applied instantly.
 *   - Never expires, but can terminate or be removed. [`New duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm#effv2_Body_0x28).
 * - 10 ⟶ **[Instant/Limited](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_10)**
 *   - This timing mode measures [`Duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xE) in ticks (1⁄15 second).
 *   - Instantly converts to [`Absolute duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm#effv2_Body_0x24_4096), [`new duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm#effv2_Body_0x28).
 *   - If [`Duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xE), it won't function any differently from timing mode [`0`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_0).
 * - All effects except those with Timing mode [`9`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC_9) are removed by death.
 * - Some effects use a measurement of [`Gametime`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/gam_v2.0.htm#GAMEV2_0_Header_GameTime) in seconds, and multiply it by 15, rather than taking the exact [`Gametime`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/gam_v2.0.htm#GAMEV2_0_Header_GameTime) in ticks.
 *   - This results in them lasting longer/shorter than they should (by up to 14 ticks).
 *     - One of such effects is [Time Stop](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op231) (this is in addition to lasting half its specified [`Duration`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xE)).
 */
OUTER_SET EFF_timing_mode = 0xc

/**
 * @type {byte offset}
 * **[Dispel / Resistance](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xD)**
 * The default behaviour is that effects cannot be dispelled and ignore magic resistance.
 * - bit 0 ⟶ Can be dispelled, affected by magic resistance
 * - bit 1 ⟶ Ignores magic resistance (when used in combination with bit 0)
 * This can also be presented in the more traditional way:
 * - 0 ⟶ Natural/Nonmagical
 * - 1 ⟶ Can be dispelled/Affected by resistance
 * - 2 ⟶ Cannot be dispelled/Ignores resistance
 * - 3 ⟶ Can be dispelled/Ignores resistance
 * The only difference between `0` and `2` is that `0` will automatically convert to `2` when targeting yourself.
 */
OUTER_SET EFF_resistance = 0xd

/**
 * @type {dword offset}
 * **[Duration](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xE)**
 * - This field is measured in seconds or ticks (1⁄15 second), depending on [`Timing mode`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0xC).
 */
OUTER_SET EFF_duration = 0xe

/**
 * @type {byte offset}
 * **[Probability 1](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x12)**
 */
OUTER_SET EFF_probability1 = 0x12

/**
 * @type {byte offset}
 * **[Probability 2](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x13)**
 * - The `BG1` engine treats probability as a single word, effects are applied in the range `0–probability`.
 * - Other engines treat probability as two values. When an event fires, a random number (let us denote it by `x`) in the `0–99` range is generated. If [`Probability1`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x12), the event fires.
 *   - Some counter-intuitive cases:
 *     - if you set both [`Probability1`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x12) and [`Probability2`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x13) to `0`, you get an effect with a 1％ chance of firing (it fires whenever the random number generator spits out zero).
 *     - if you set [`Probability1`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x12) to `1` and [`Probability2`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x13) to `0` (as, e.g., happens in BGT/BGEE's implementation of the iron crisis), you don't get an effect with a 1％ chance of firing, but one with a 2％ chance of firing.
 * - An effect's probabilities are rolled on the sprite the effect is applied to. This means that an effect targeting [`Projectile Target`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_2) will have the target roll that effect's probabilities, not the attacker or caster. This decouples the split probability roll and allows both to occur at the same time, since each sprite rolls separately. As a consequence it is not directly possible to synchronize effects with partial probabilities that are applied to different targets (e.g. [`Projectile Target`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_2) and [`Self`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x2_1)).
 */
OUTER_SET EFF_probability2 = 0x13

/**
 * @type {resref offset}
 * **[Resref key](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_Resource)**
 */
OUTER_SET EFF_resref_key = 0x14

/**
 * @type {dword offset}
 * **[Dice Thrown / Maximum Level](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x1C)**
 * - When this field is non-zero, all opcodes except for [opcode #12](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op12), [opcode #17](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op17), [opcode #18](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op18), [opcode #218](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op218) (only when `parameter2=1`), [opcode #331](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op331), and [opcode #333](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op333), treat it as `Maximum Level`, meaning that only creatures whose level attribute is less than or equal to this value will be affected by the effect.
 * When this field is used as `Maximum Level`:
 * - A `7 ➔ 1` dual-class character qualifies as HD 7, even though the level 7 class is still inactive.
 * - A `1/7/1` multi-class character qualifies as HD 7, not level 3 (average).
 * - The [2nd](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/cre_v1.htm#CREV1_0_Header_0x235)/[3rd](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/cre_v1.htm#CREV1_0_Header_0x236) class levels are NOT included for single-classes.
 *   - A `1/30/1` single-class character qualifies as HD 1.
 */
OUTER_SET EFF_dice_thrown = 0x1c

/**
 * @type {dword offset}
 * **[Dice Sides / Minimum Level](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x20)**
 * - When this field is non-zero, all opcodes except for [opcode #12](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op12), [opcode #17](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op17), [opcode #18](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op18), [opcode #218](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op218) (only when `parameter2=1`), [opcode #331](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op331), and [opcode #333](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op333), treat it as `Minimum Level`, meaning that only creatures whose level attribute is greater than or equal to this value will be affected by the effect.
 * When this field is used as `Minimum Level`:
 * - A `7 ➔ 1` dual-class character qualifies as HD 7, even though the level 7 class is still inactive.
 * - A `1/7/1` multi-class character qualifies as HD 7, not level 3 (average).
 * - The [2nd](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/cre_v1.htm#CREV1_0_Header_0x235)/[3rd](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/cre_v1.htm#CREV1_0_Header_0x236) class levels are NOT included for single-classes.
 *   - A `1/30/1` single-class qualifies as HD 1.
 */
OUTER_SET EFF_dice_sides = 0x20

/**
 * @type {dword offset}
 * **[Saving throw type](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x24)**
 * - bit 0 ⟶ **[Spells](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x24_BIT0)**
 * - bit 1 ⟶ **[Breath](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x24_BIT1)**
 * - bit 2 ⟶ **[Paralyze / Poison / Death](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x24_BIT2)**
 * - bit 3 ⟶ **[Wands](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x24_BIT3)**
 * - bit 4 ⟶ **[Petrify / Polymorph](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x24_BIT4)**
 * - bit 5 ⟶ **Spells** (EE only)
 *   - see **opcode #322**
 * - bit 6 ⟶ **Breath** (EE only)
 *   - see **opcode #322**
 * - bit 7 ⟶ **Paralyze / Poison / Death** (EE only)
 *   - see **opcode #322**
 * - bit 8 ⟶ **Wands** (EE only)
 *   - see **opcode #322**
 * - bit 9 ⟶ **Petrify / Polymorph** (EE only)
 *   - see **opcode #322**
 * - bit 10 ⟶ **[Ignore primary target](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x24_BIT10)** (EE only)
 *   - [Line AoE projectile](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/pro_v1.htm#ExtFlags_BIT14) doesn't affect end target.
 * - bit 11 ⟶ **[Ignore secondary target](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x24_BIT11)** (EE only)
 *   - [Line AoE projectile](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/pro_v1.htm#ExtFlags_BIT14) doesn't affect bystanders.
 * - bit 24 ⟶ **[Bypass mirror image](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x24_BIT24)** (EE/TobEx only)
 *   - This bit is only relevant for [opcode #12](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op12) and [opcode #25](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op25).
 *   - All other opcodes bypass Mirror Image by default, setting/unsetting this bit is harmless.
 * - bit 25 ⟶
 *   - **[Ignore difficulty](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x24_BIT25_EE)** (EE only)
 *     - This bit is specific to [opcode #12](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op12) only.
 *     - It refers to the damage multiplier to Party Members based on Game Difficulty.
 *   - **[Limit effect stacking](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm#effv1_Header_0x24_BIT25_ToBEx)** (ToBEx only)
 * - bit 26 ⟶ TobEx internal (don't use)
 *   - Suspends effect application.
 * If more than 1 Saving Throw Type is specified (`BIT0 – BIT4`), the target rolls against their best save.
 */
OUTER_SET EFF_save_type = 0x24

/**
 * @type {dword offset}
 * Saving throw bonus
 */
OUTER_SET EFF_save_bonus = 0x28
