/**
 * @type {char offset}
 * Spell form
 *   - 1 - Standard
 *   - 2 - Projectile
 * This field matters only for [`ITM`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x0), SPL files shouldn't function any different based on their type (even `0`).
 */
OUTER_SET SPL_HEAD_form = 0x0

/**
 * @type {char offset}
 * - bit 2: 'Friendly' ability (PST only)
 */
OUTER_SET SPL_HEAD_friendly = 0x1

/**
 * @type {word offset}
 * **[Location](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0x2)**
 * - 0 ⟶ None
 *   - Ability will not be selectable through the UI (but still available to scripts and spell-casting opcodes).
 * - 1 ⟶ Weapon
 *   - [`ITM`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x2_1) only.
 * - 2 ⟶ **[Spell](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0x2_2)**
 *   - Ability can be selected from "Cast Spell (F7)" button, and from Quick-spell buttons.
 * - 3 ⟶ Item
 *   - [`ITM`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm#itmv1_Extended_Header_0x2_3) only.
 * - 4 ⟶ **[Innate](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0x2_4)**
 *   - Ability can be selected from "Special Abilities (F12)" button.
 * - 5+ ⟶ As `0`.
 * Subspells don't require an [`Ability Location`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0x2).
 */
OUTER_SET SPL_HEAD_location = 0x2

/**
 * @type {resref offset}
 * Memorised icon (BAM). The engine replaces the last character of this filename with a B.
 */
OUTER_SET SPL_HEAD_memorised_icon = 0x4

/**
 * @type {char offset}
 * **[Target](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0xC)**
 * - 0 ⟶ Invalid (cannot be selected)
 * - 1 ⟶ **[Living actor](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0xC_1)**
 *   - Targets Portrait, [Creature/Actor](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v1.htm#formAREAV1_0_Actor), [Container](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v1.htm#formAREAV1_0_Container), or [Door](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v1.htm#formAREAV1_0_Door). Checks [`Range`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0xE).
 * - 2 ⟶ **[Inventory](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0xC_2)**
 *   - Can't be activated manually.
 * - 3 ⟶ **[Dead actor](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0xC_3)**
 *   - As [`Living Actor`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0xC_1). It really just ignores any [`Range`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0xE) requirement, including being in the same area.
 * - 4 ⟶ **[Any point within range](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0xC_4)**
 *   - Targets location. Checks [`Range`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0xE).
 * - 5 ⟶ **[Caster](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0xC_5)**
 *   - Targets Self.
 * - 6 ⟶ Crash
 *   - Can't be activated manually.
 * - 7 ⟶ **[Caster](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0xC_7)**
 *   - Targets Self. In particular:
 *     - Cast instantly (even while the game is paused).
 *     - Ignores one spell per round rule.
 *     - Ignores [Silence](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op38), [Spell Failure](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op60), [Dead Magic](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op60), [Wild Surge](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op280), [`Outdoors Only`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#Header_Flags_BIT13), [`Non-combat`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#Header_Flags_BIT16), probably a few other rules.
 * - This field doesn't matter when the ability is activated/cast by script or when cast by another opcode.
 * - Subspells don't require an [`Ability Target`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0xC).
 */
OUTER_SET SPL_HEAD_target = 0xc

/**
 * @type {char offset}
 * **[Target count](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0xD)**
 * - Only usable with Ability Targets [`1`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0xC_1), [`3`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0xC_3), or [`4`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0xC_4).
 * - Targeting reticle will display amount remaining while selecting targets.
 * - Double-clicking a target/location will target it for the remaining amount.
 * - Regardless of the number of targets, only a single "Memorization" will be expended.
 * - This feature cannot be utilized by scripts.
 *   - Scripts will treat this field as if it's always `1`.
 */
OUTER_SET SPL_HEAD_target_count = 0xd

/**
 * @type {word offset}
 * **[Range](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0xE)**
 * As far as subspells are concerned, their [`Range`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0xE) is only checked if cast through [opcode #148](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op148), [opcode #232](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op232), [opcode #258](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op258), or [opcode #260](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op260).
 */
OUTER_SET SPL_HEAD_range = 0xe

/**
 * @type {word offset}
 * **[Level Required](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0x10)**
 * Standard spellcasting only utilizes the first byte (`0 – 255`), but opcodes that specify Casting Level ([`146`](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op146)/[`326`](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op326)/[`333`](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op333)) have access to the entire range (`0 – 65535`).
 */
OUTER_SET SPL_HEAD_level_required = 0x10

/**
 * @type {word offset}
 * **[Casting Time](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0x12)**
 * - This value represents the number of tenths of rounds that it takes to cast the spell.
 * - Combat scripting in the IE gets very dumb when [`Casting Time`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0x12)s start matching or exceeding `10` (one full round). The engine assumes any spell is cast within a round, and can sometimes just go to the next round's action (f.i. the mage sits there casting for six seconds, then throws the spell away to use a sling).
 *   - As a result, you might want to use maximum [`Casting Time`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0x12)s of `9` (i.e. 9⁄10ths of a round) even for spells which are supposed to have a [`Casting Time`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0x12) of a full round.
 * - As far as subspells are concerned, their speed is only used if cast through [opcode #146](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op146)/[opcode #148](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op148) with the `Cast normally` option.
 */
OUTER_SET SPL_HEAD_casting_time = 0x12

/**
 * @type {word offset}
 * Times per day
 */
OUTER_SET SPL_HEAD_times_per_day = 0x14

/**
 * @type {word offset}
 * Count of feature blocks
 */
OUTER_SET SPL_HEAD_feature_blocks_count = 0x1e

/**
 * @type {word offset}
 * Offset to feature blocks
 */
OUTER_SET SPL_HEAD_feature_blocks_offset = 0x20

/**
 * @type {word offset}
 * **[Projectile](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0x26)** (BG2: [projectl.ids](https://gibberlings3.github.io/iesdp/ids/bg2/projectl.htm). **Note:** in BG2, this value is off-by-one from projectl.ids value. I.e. binary value of `2` corresponds to `0x1 - ARROW`)
 */
OUTER_SET SPL_HEAD_projectile = 0x26

/**
 * @type {char array offset}
 * Signature ('SPL  ')
 */
OUTER_SET SPL_signature = 0x0

/**
 * @type {char array offset}
 * Version ('V1  ')
 */
OUTER_SET SPL_version = 0x4

/**
 * @type {dword offset}
 * **[Spell Name](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x8)** - Unidentified (strref)
 */
OUTER_SET SPL_unidentified_name = 0x8

/**
 * @type {resref offset}
 * Completion Sound
 */
OUTER_SET SPL_completion_sound = 0x10

/**
 * @type {dword offset}
 * [Flags](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#Header_Flags)
 */
OUTER_SET SPL_flags = 0x18

/**
 * @type {word offset}
 * **[Spell type](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C)**:
 * - 0 ⟶ **[Special](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_0)**
 * - 1 ⟶ **[Wizard](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_1)**
 * - 2 ⟶ **[Priest](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_2)**
 * - 3 ⟶ **[Psionic](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_3)**
 * - 4 ⟶ **[Innate](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_4)**
 * - 5 ⟶ **[Bard song](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_5)**
 * - [`Special`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_0), [`Psionic`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_3), [`Innate`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_4), and [`Bard song`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_5) differ only by the string displayed when you cast them. They are all treated as [`Innate`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_4) abilities, even by [opcode #145](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op145) and the [`SpellCastInnate()`](https://gibberlings3.github.io/iesdp/scripting/triggers/bgeetriggers.htm#0x00A7) trigger.
 * - [`Special`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_0) and [`Innate`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_4) will display [`spell name`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x8).
 * - [`Psionic`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_3) and [`Bard song`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_5) will display [`spell name`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x8) (which can be misleading).
 * - [`Wizard`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_1) and [`Priest`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_2) will also display [`spell name`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x8).
 * - Any spell cast by one of the [`ForceSpell()`](https://gibberlings3.github.io/iesdp/scripting/actions/bgeeactions.htm#113) script actions will instead display [`Special`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_0)/[`Innate`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_4) casting message.
 * - Any spell cast by the "BattleSong" (Bard Song/Shaman Dance) or [`ApplySpell()`](https://gibberlings3.github.io/iesdp/scripting/actions/bgeeactions.htm#160) script actions will display [`Special`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_0)/[`Innate`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_4) casting message.
 * - For any spell cast by another opcode, its casting message will depend on that opcode, but is usually the same as the [`Special`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_0)/[`Innate`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_4) casting message.
 * - All other values (`6 – 65535`) functions the same as [`Psionic`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_3)/[`Bard song`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_5).
 * - [`SPELLFAILUREMAGE`](https://gibberlings3.github.io/iesdp/files/ids/bgee/stats.htm#51) is related to Spell type [`Wizard`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_1).
 * - [`SPELLFAILUREPRIEST`](https://gibberlings3.github.io/iesdp/files/ids/bgee/stats.htm#52) is related to Spell type [`Priest`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_2).
 * - [`SPELL_FAILURE_INNATE`](https://gibberlings3.github.io/iesdp/files/ids/bgee/stats.htm#194) is related to Spell type [`Psionic`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_3)/[`Innate`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_4)/[`Bard song`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_5).
 * - Normally, any subspells that scale with [`Level`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Extended_Header_0x10) should be of the same [`Type`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C) as the spell casting them.
 *   - If they don't scale, it doesn't really matter.
 *   - It also doesn't matter when they are applied through [opcode #146](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op146)`*p2=2`/[opcode #326](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op326)/[opcode #333](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op333).
 */
OUTER_SET SPL_type = 0x1c

/**
 * @type {dword offset}
 * [Exclusion Flags](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#Exclusion_Flags)
 */
OUTER_SET SPL_exclusion_flags = 0x1e

/**
 * @type {word offset}
 * [Casting Graphics](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#Header_Casting_Graphics)
 */
OUTER_SET SPL_casting_graphics = 0x22

/**
 * @type {byte offset}
 * **[Primary Type (School)](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x25)** (IWD: school.2da, BG2:mschool.2da)
 * For subspells, [`Primary Type`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x25) should always match parent spell, both for interaction with opcodes [#220](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op220)/[#229](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op229), and with the specialists save bonus/penalty (and [opcode #346](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op346)).
 */
OUTER_SET SPL_school = 0x25

/**
 * @type {char offset}
 * **[Secondary Type](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x27)** (BG2:msectype.2da)
 * For subspells, [`Secondary Type`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x27) should always match parent spell, for interaction with opcodes [#221](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op221)/[#230](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op230).
 */
OUTER_SET SPL_sectype = 0x27

/**
 * @type {dword offset}
 * **[Spell Level](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x34)**
 * - There is no good reason for a [`Special`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_0)/[`Psionic`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_3)/[`Innate`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_4)/[`Bard song`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x1C_5) to be any [`Spell level`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x34) except `1`.
 * - If the SPL is never [learned](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op147)/[gained](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op171) (only force-cast by script/opcode), [`Spell level`](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm#splv1_Header_0x34) doesn't matter, but there may be some niche cases that check it (f.i. [`HaveSpell()`](https://gibberlings3.github.io/iesdp/scripting/triggers/bgeetriggers.htm#0x4031)).
 */
OUTER_SET SPL_level = 0x34

/**
 * @type {resref offset}
 * Spellbook icon (BAM). The engine replaces the last character of this filename with a C.
 */
OUTER_SET SPL_spellbook_icon = 0x3a

/**
 * @type {dword offset}
 * Spell Description
 */
OUTER_SET SPL_description = 0x50

/**
 * @type {dword offset}
 * Extended Header offset
 */
OUTER_SET SPL_extended_headers_offset = 0x64

/**
 * @type {word offset}
 * Extended Header count
 */
OUTER_SET SPL_extended_headers_count = 0x68

/**
 * @type {dword offset}
 * Feature Block Table offset
 */
OUTER_SET SPL_feature_blocks_offset = 0x6a

/**
 * @type {word offset}
 * Casting Feature Block offset (these feature blocks may not use target type 2)
 */
OUTER_SET SPL_casting_feature_blocks_offset = 0x6e

/**
 * @type {word offset}
 * Casting Feature Block count
 */
OUTER_SET SPL_casting_feature_blocks_count = 0x70
